filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/logstash/logstash-plain.log
    - /var/log/logstash/logstash-slowlog-plain.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "http://kibana:5601"
